make:
	$ java -cp ../antlr-3.5.2-complete.jar org.antlr.Tool myChecker.g
	$ javac -cp ../antlr-3.5.2-complete.jar:. myChecker_test.java 
	$ java -cp ../antlr-3.5.2-complete.jar:. myChecker_test test1.c
	$ java -cp ../antlr-3.5.2-complete.jar:. myChecker_test test2.c
	$ java -cp ../antlr-3.5.2-complete.jar:. myChecker_test test3.c