make:
	$ java -cp ../antlr-3.5.2-complete.jar org.antlr.Tool myCompiler.g
	$ javac -cp ../antlr-3.5.2-complete.jar:. myCompiler_test.java 
	$ java -cp ../antlr-3.5.2-complete.jar:. myCompiler_test test1.c > test1.ll
	$ java -cp ../antlr-3.5.2-complete.jar:. myCompiler_test test2.c > test2.ll
	$ java -cp ../antlr-3.5.2-complete.jar:. myCompiler_test test3.c > test3.ll