make:
	$ java -cp ../antlr-3.5.2-complete.jar org.antlr.Tool mylexer.g
	$ javac -cp ../antlr-3.5.2-complete.jar testLexer.java mylexer.java
	$ java -cp ../antlr-3.5.2-complete.jar:. testLexer testing_program1.c
	$ java -cp ../antlr-3.5.2-complete.jar:. testLexer testing_program2.c
	$ java -cp ../antlr-3.5.2-complete.jar:. testLexer testing_program3.c
